meta_product_name: "KapTrack"
meta_title: "KapTrack - oversee your success"
meta_description: "A single platform, a multitude of services"
meta_image: "https://files.slack.com/files-pri/T02NE0241-F01G6C3PS9M/image.png"
twitter_account: "@product_twitter_account"   # required for Twitter Cards